name: shealth_downloader
description: A downloader of Samsung Health data.
version: 0.1.0
repository: https://github.com/inexcode/shealth-downloader

environment:
  sdk: ^3.4.4

dependencies:
  dio: ^5.5.0+1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mongo_dart: ^0.10.3

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
